services:
  client-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "6004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ClientDB;User Id=sa;Password=SuaSenhaForte123@;Encrypt=False;TrustServerCertificate=True
    networks:
      - fasttechfood-network
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-client
    environment:
      SA_PASSWORD: "SuaSenhaForte123@"
      ACCEPT_EULA: "Y"
    networks:
      - fasttechfood-network
    ports:
      - "1433:1433"

networks:
  fasttechfood-network:
    driver: bridge