apiVersion: v1
kind: ConfigMap
metadata:
  name: client-api-config
data:
  DefaultConnection: "Server=sqlserver;Database=FastTechFoods.ClientDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True"
